### ISSUE TITLE
Some ideas (authentication bug, timeout, more...)

### ISSUE THREAD

**Issue by d0k3** [jordanbtucker/WiiPair#1]
I actually wanted to do a pull request, but consider me defeated by VS studio setup (I'm a GCC person). First of all: thanks for this useful tool.

Here's some ideas (no specific order):

1. That other WiiPair fork by @jmandawg can also remove existing pairings before adding new pairings. As WiiMote pairing can be wonky, that's pretty helpful sometimes. Shouldn't be done by default, of course, and it's best solved via some command line parameter.
2. Instead of stopping after at least 1 WiiMote is paired, can you just make WiiPair search for x seconds (300 sounds good) or until some key is pressed? Maybe let the user specify the timeout via command line?
3. That bluetooth authentication bug is not a bug. See [here](https://wiibrew.org/wiki/Wiimote#Bluetooth_Pairing). The correct bluetooth PIN depends on wether you pressed the red sync button or the 1+2 button combo. Don't undo this fix, in fact, prefer the 1+2 button combo as you do now. You could try the other PIN if one fails, though. This would especially be helpful with third party WiiMotes (which don't always act the same as Nintendos official ones).

**Comment by jordanbtucker** [comment]
Thanks for these ideas, especially the info about the Bluetooth PIN. I don't really have time to make any of these changes right now, and I'm not really a C++ developer. I adapted this from someone else's code. Feel free to fork and make it work with GCC.
